tabWidth: 2
useTabs: true
printWidth: 80
proseWrap: preserve
trailingComma: none
plugins:
  - prettier-plugin-astro
overrides:
  - files: "*.astro"
    options:
      parser: astro
  - files: "*.svelte"
    options:
      parser: svelte
